from .certificationmodel import *
from .classmodel import *
from .trainingclassmodel import *
from .ondutymodel import *
from .resultmodel import *
from .resultextramodel import *
from .textbookmodel import *
from .totalmodel import *
from .tuitionmodel import *
from .wechatmodel import *