# Generated by Django 2.2.5 on 2020-05-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marriagebasic',
            name='mar_qq',
        ),
        migrations.RemoveField(
            model_name='marriagebasic',
            name='mar_teacher_level',
        ),
        migrations.AddField(
            model_name='marriagebasic',
            name='mar_email',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='marriagebasic',
            name='mar_group',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='组别和职务'),
        ),
        migrations.AddField(
            model_name='marriagebasic',
            name='mar_type',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员类型'),
        ),
    ]
