# Generated by Django 2.2.5 on 2020-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0002_auto_20200511_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriageexam',
            name='exam_practice',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国考技能分'),
        ),
        migrations.AlterField(
            model_name='marriagetextbook',
            name='text_basic',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='基础知识'),
        ),
    ]
