from .classmodel import *
from .familymodel import *
from .tuitionmodel import *
from .textbookmodel import *
from .wechatmodel import *
from .resultmodel import *
from .resultextramodel import *
from .certificationmodel import *
from .ondutymodel import *
from .totalmodel import *