# Generated by Django 2.2.5 on 2020-05-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxtextbook',
            name='text_basic',
        ),
        migrations.RemoveField(
            model_name='sandboxtextbook',
            name='text_skill',
        ),
        migrations.RemoveField(
            model_name='sandboxtextbook',
            name='text_workbook',
        ),
        migrations.AddField(
            model_name='sandboxtextbook',
            name='text_sandbox',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='沙盘教材'),
        ),
        migrations.AddField(
            model_name='sandboxtextbook',
            name='text_three',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='教材3'),
        ),
        migrations.AddField(
            model_name='sandboxtextbook',
            name='text_two',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='教材2'),
        ),
    ]
