# Generated by Django 2.2.5 on 2019-10-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_number', models.CharField(max_length=128, unique=True, verbose_name='学号')),
                ('fam_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('fam_gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=16, null=True, verbose_name='性别')),
                ('fam_level', models.CharField(blank=True, choices=[('二级', '二级'), ('三级', '三级')], max_length=16, null=True, verbose_name='级别')),
                ('fam_id_number', models.CharField(max_length=128, unique=True, verbose_name='身份证号')),
                ('fam_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='所在地')),
                ('fam_deg', models.CharField(blank=True, max_length=128, null=True, verbose_name='学历')),
                ('fam_major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('fam_company', models.CharField(blank=True, max_length=128, null=True, verbose_name='工作单位')),
                ('fam_duty', models.CharField(blank=True, max_length=128, null=True, verbose_name='职务')),
                ('fam_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='职称')),
                ('fam_origin', models.CharField(blank=True, max_length=128, null=True, verbose_name='生源来源')),
                ('fam_cellphone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号')),
                ('fam_wechat', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信')),
                ('fam_qq', models.CharField(blank=True, max_length=128, null=True, verbose_name='QQ')),
                ('fam_signup_date', models.DateField(blank=True, null=True, verbose_name='报名日期')),
                ('fam_signup_people', models.CharField(blank=True, max_length=128, null=True, verbose_name='具体招生人')),
                ('fam_teacher_level', models.CharField(blank=True, max_length=32, null=True, verbose_name='心师级别')),
                ('fam_other', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('fam_class_num', models.CharField(blank=True, max_length=128, null=True, verbose_name='班内序号')),
            ],
            options={
                'verbose_name': '家庭招生信息',
                'verbose_name_plural': '家庭招生信息',
            },
        ),
        migrations.CreateModel(
            name='FamilyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_recruit_teacher', models.CharField(blank=True, max_length=64, null=True, verbose_name='招生老师')),
                ('class_teacher', models.CharField(blank=True, max_length=64, null=True, verbose_name='跟班老师')),
                ('class_date', models.CharField(blank=True, max_length=64, null=True, verbose_name='开班年份')),
                ('class_name', models.CharField(max_length=64, verbose_name='班级名')),
            ],
            options={
                'verbose_name': '家庭班级',
                'verbose_name_plural': '家庭班级',
            },
        ),
        migrations.CreateModel(
            name='FamilyCertification',
            fields=[
                ('relate_family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='family.FamilyBasic', verbose_name='学号')),
                ('cert_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='证书编号')),
                ('cert_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('cert_draw_people', models.CharField(blank=True, max_length=128, null=True, verbose_name='领取人')),
                ('cert_draw_date', models.DateField(blank=True, null=True, verbose_name='领取时间')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
            },
        ),
        migrations.CreateModel(
            name='FamilyTextbook',
            fields=[
                ('relate_family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='family.FamilyBasic', verbose_name='学号')),
                ('text_basic', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭婚姻动力学')),
                ('text_other', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '家庭教材',
                'verbose_name_plural': '家庭教材',
            },
        ),
        migrations.CreateModel(
            name='FamilyTuition',
            fields=[
                ('relate_family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='family.FamilyBasic', verbose_name='学号')),
                ('fee_train', models.CharField(blank=True, max_length=128, null=True, verbose_name='培训费')),
                ('fee_date', models.DateField(blank=True, null=True, verbose_name='缴费日期')),
                ('fee_method', models.CharField(blank=True, max_length=128, null=True, verbose_name='缴费方式')),
                ('fee_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='收据号')),
                ('fee_tax', models.CharField(blank=True, max_length=128, null=True, verbose_name='发票号')),
            ],
            options={
                'verbose_name': '家庭交费信息',
                'verbose_name_plural': '家庭交费信息',
            },
        ),
        migrations.CreateModel(
            name='FamilyWechat',
            fields=[
                ('relate_family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='family.FamilyBasic', verbose_name='学号')),
                ('wechat_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='平台绑定号码')),
                ('wechat_nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信昵称')),
                ('wechat_date', models.CharField(blank=True, max_length=128, null=True, verbose_name='开通网课')),
            ],
            options={
                'verbose_name': '家庭365开通情况',
                'verbose_name_plural': '家庭365开通情况',
            },
        ),
        migrations.CreateModel(
            name='ResultExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='补考日期')),
                ('homework_two_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业二成绩')),
                ('homework_three_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业三成绩')),
                ('result', models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], max_length=64, null=True, verbose_name='合格情况')),
                ('relate_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '家庭补考成绩',
                'verbose_name_plural': '家庭补考成绩',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='考核日期')),
                ('homework_two_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业二成绩')),
                ('homework_three_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业三成绩')),
                ('result', models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], max_length=64, null=True, verbose_name='合格情况')),
                ('relate_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '家庭考核成绩',
                'verbose_name_plural': '家庭考核成绩',
            },
        ),
        migrations.CreateModel(
            name='FamilyOnduty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onduty', models.CharField(blank=True, max_length=128, null=True, verbose_name='出勤')),
                ('homework1', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业一')),
                ('homework2', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业二')),
                ('homework3', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业三')),
                ('other', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('relate_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '家庭考勤信息',
                'verbose_name_plural': '家庭考勤信息',
            },
        ),
        migrations.AddField(
            model_name='familybasic',
            name='fam_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
    ]
