# Generated by Django 2.2.5 on 2019-10-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familycertification',
            options={'verbose_name': '家庭证书', 'verbose_name_plural': '家庭证书'},
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_signup_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='报名日期'),
        ),
        migrations.AlterField(
            model_name='familycertification',
            name='cert_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='发证日期'),
        ),
        migrations.AlterField(
            model_name='familytuition',
            name='fee_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='缴费日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='考核日期'),
        ),
        migrations.AlterField(
            model_name='resultextra',
            name='date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='补考日期'),
        ),
    ]
