# Generated by Django 2.2.5 on 2019-10-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20191024_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familybasic',
            name='fam_id_number',
            field=models.CharField(max_length=128, verbose_name='身份证号'),
        ),
    ]
