# Generated by Django 2.2.5 on 2019-10-31 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_auto_20191029_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familybasic',
            name='fam_cellphone',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_class_num',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='班内序号'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_company',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='工作单位'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_deg',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_duty',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='空', max_length=16, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_id_number',
            field=models.CharField(default='空', max_length=128, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_level',
            field=models.CharField(blank=True, choices=[('二级', '二级'), ('三级', '三级')], default='空', max_length=16, null=True, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_loc',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_major',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_name',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_origin',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='生源来源'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_other',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_qq',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_signup_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='报名日期'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_signup_people',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='具体招生人'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_status',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_teacher_level',
            field=models.CharField(blank=True, default='空', max_length=32, null=True, verbose_name='心师级别'),
        ),
        migrations.AlterField(
            model_name='familybasic',
            name='fam_wechat',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='familycertification',
            name='cert_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发证日期'),
        ),
        migrations.AlterField(
            model_name='familycertification',
            name='cert_draw_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='familycertification',
            name='cert_draw_people',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='领取人'),
        ),
        migrations.AlterField(
            model_name='familycertification',
            name='cert_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='证书编号'),
        ),
        migrations.AlterField(
            model_name='familyclass',
            name='class_date',
            field=models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='开班年份'),
        ),
        migrations.AlterField(
            model_name='familyclass',
            name='class_recruit_teacher',
            field=models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='招生老师'),
        ),
        migrations.AlterField(
            model_name='familyclass',
            name='class_teacher',
            field=models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='跟班老师'),
        ),
        migrations.AlterField(
            model_name='familyonduty',
            name='homework1',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业一'),
        ),
        migrations.AlterField(
            model_name='familyonduty',
            name='homework2',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业二'),
        ),
        migrations.AlterField(
            model_name='familyonduty',
            name='homework3',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业三'),
        ),
        migrations.AlterField(
            model_name='familyonduty',
            name='onduty',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='familyonduty',
            name='other',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='familytextbook',
            name='text_basic',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='家庭婚姻动力学'),
        ),
        migrations.AlterField(
            model_name='familytextbook',
            name='text_other',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='familytuition',
            name='fee_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费日期'),
        ),
        migrations.AlterField(
            model_name='familytuition',
            name='fee_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='收据号'),
        ),
        migrations.AlterField(
            model_name='familytuition',
            name='fee_method',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费方式'),
        ),
        migrations.AlterField(
            model_name='familytuition',
            name='fee_tax',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票号'),
        ),
        migrations.AlterField(
            model_name='familytuition',
            name='fee_train',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='培训费'),
        ),
        migrations.AlterField(
            model_name='familywechat',
            name='wechat_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='开通网课'),
        ),
        migrations.AlterField(
            model_name='familywechat',
            name='wechat_nickname',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信昵称'),
        ),
        migrations.AlterField(
            model_name='familywechat',
            name='wechat_number',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='平台绑定号码'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='考核日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='homework_three_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业三成绩'),
        ),
        migrations.AlterField(
            model_name='result',
            name='homework_two_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业二成绩'),
        ),
        migrations.AlterField(
            model_name='result',
            name='relate_family',
            field=models.OneToOneField(blank=True, default='空', null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyBasic', verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], default='空', max_length=64, null=True, verbose_name='合格情况'),
        ),
        migrations.AlterField(
            model_name='resultextra',
            name='date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='补考日期'),
        ),
        migrations.AlterField(
            model_name='resultextra',
            name='homework_three_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业三成绩'),
        ),
        migrations.AlterField(
            model_name='resultextra',
            name='homework_two_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业二成绩'),
        ),
        migrations.AlterField(
            model_name='resultextra',
            name='result',
            field=models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], default='空', max_length=64, null=True, verbose_name='合格情况'),
        ),
    ]
