# Generated by Django 2.2.5 on 2019-11-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20191031_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycertification',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='familyclass',
            name='class_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='班级序号'),
        ),
        migrations.AddField(
            model_name='familyonduty',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='familytextbook',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='familytuition',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='familywechat',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='result',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='resultextra',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='班级'),
        ),
    ]
