# Generated by Django 2.2.5 on 2019-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_familyclass_class_id_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familybasic',
            name='fam_level',
        ),
        migrations.RemoveField(
            model_name='familyonduty',
            name='homework1',
        ),
        migrations.RemoveField(
            model_name='familyonduty',
            name='homework2',
        ),
        migrations.RemoveField(
            model_name='familyonduty',
            name='homework3',
        ),
        migrations.AddField(
            model_name='familytextbook',
            name='text_manual',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员手册'),
        ),
        migrations.AddField(
            model_name='result',
            name='homework_one_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业一成绩'),
        ),
        migrations.AlterField(
            model_name='familytextbook',
            name='text_basic',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='教材'),
        ),
    ]
