# Generated by Django 2.2.5 on 2019-12-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0010_resultextra_homework_one_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familywechat',
            name='wechat_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='开通日期'),
        ),
    ]
