# Generated by Django 2.2.5 on 2020-03-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0011_auto_20191203_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total',
            options={'verbose_name': '家庭信息总览', 'verbose_name_plural': '家庭信息总览'},
        ),
        migrations.AddField(
            model_name='familytuition',
            name='fee_invoice_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票开票日期'),
        ),
        migrations.AddField(
            model_name='familytuition',
            name='fee_invoice_header',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票抬头'),
        ),
        migrations.AddField(
            model_name='familytuition',
            name='fee_invoice_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票机构代码'),
        ),
    ]
