# Generated by Django 2.2.5 on 2020-05-10 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0012_auto_20200327_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='relate_family',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.FamilyBasic', verbose_name='学号'),
        ),
    ]
