# Generated by Django 2.2.5 on 2020-05-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0014_auto_20200514_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyonduty',
            name='homework',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='视频提交'),
        ),
    ]
