# Generated by Django 2.2.5 on 2020-11-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tra_type', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员类型')),
                ('tra_number', models.CharField(max_length=128, unique=True, verbose_name='学号')),
                ('tra_group', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='组名与职务')),
                ('tra_name', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='姓名')),
                ('tra_gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='空', max_length=16, null=True, verbose_name='性别')),
                ('tra_id_number', models.CharField(default='空', max_length=128, verbose_name='身份证号')),
                ('tra_loc', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='所在地')),
                ('tra_deg', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学历')),
                ('tra_major', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='专业')),
                ('tra_company', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='工作单位')),
                ('tra_duty', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职务')),
                ('tra_status', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职称')),
                ('tra_origin', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='生源来源')),
                ('tra_cellphone', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='手机号')),
                ('tra_wechat', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信')),
                ('tra_qq', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='邮箱')),
                ('tra_signup_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='报名日期')),
                ('tra_signup_people', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='具体招生人')),
                ('tra_teacher_level', models.CharField(blank=True, default='空', max_length=32, null=True, verbose_name='心师级别')),
                ('tra_other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('tra_class_num', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='班内序号')),
            ],
            options={
                'verbose_name': '训练班招生信息',
                'verbose_name_plural': '训练班招生信息',
            },
        ),
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=64, verbose_name='班级名')),
                ('class_index', models.IntegerField(blank=True, null=True, verbose_name='班级序号')),
                ('class_id_example', models.CharField(blank=True, max_length=128, null=True, verbose_name='学号命名')),
                ('class_recruit_teacher', models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='招生老师')),
                ('class_teacher', models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='跟班老师')),
                ('class_date', models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='开班年份')),
            ],
            options={
                'verbose_name': '训练班级',
                'verbose_name_plural': '训练班级',
            },
        ),
        migrations.CreateModel(
            name='TrainOnduty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onduty', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='出勤')),
                ('homework', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='视频提交')),
                ('other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级')),
                ('relate_trainingclass', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '训练班考勤信息',
                'verbose_name_plural': '训练班考勤信息',
            },
        ),
        migrations.AddField(
            model_name='trainbasic',
            name='tra_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级'),
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainBasic', verbose_name='学生')),
            ],
            options={
                'verbose_name': '训练班信息总览',
                'verbose_name_plural': '训练班信息总览',
            },
        ),
        migrations.CreateModel(
            name='ResultExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_one_result', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业一成绩')),
                ('date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='补考日期')),
                ('homework_two_result', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业二成绩')),
                ('homework_three_result', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业三成绩')),
                ('result', models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], default='空', max_length=64, null=True, verbose_name='合格情况')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级')),
                ('relate_trainingclass', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '训练班补考成绩',
                'verbose_name_plural': '训练班补考成绩',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_one_result', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业一成绩')),
                ('date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='考核日期')),
                ('homework_two_result', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业二成绩')),
                ('homework_three_result', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业三成绩')),
                ('result', models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], default='空', max_length=64, null=True, verbose_name='合格情况')),
                ('total', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='总分')),
                ('nation_result', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国考笔试成绩')),
                ('pre', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='说课分')),
                ('speech', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='宣讲分')),
                ('other', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级')),
                ('relate_trainingclass', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '训练班考核成绩',
                'verbose_name_plural': '训练班考核成绩',
            },
        ),
        migrations.CreateModel(
            name='TrainWechat',
            fields=[
                ('relate_trainingclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trainingClass.TrainBasic', verbose_name='学号')),
                ('wechat_number', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='平台绑定号码')),
                ('wechat_nickname', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信昵称')),
                ('wechat_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='开通日期')),
                ('wechat_other', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '训练班365开通情况',
                'verbose_name_plural': '训练班365开通情况',
            },
        ),
        migrations.CreateModel(
            name='TrainTuition',
            fields=[
                ('relate_trainingclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trainingClass.TrainBasic', verbose_name='学号')),
                ('fee_train', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='培训费')),
                ('fee_material', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='资料费')),
                ('fee_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费日期')),
                ('fee_method', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费方式')),
                ('fee_id', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='收据号')),
                ('fee_tax', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票号')),
                ('fee_invoice_header', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票抬头')),
                ('fee_invoice_id', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票机构代码')),
                ('fee_invoice_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票开票日期')),
                ('fee_invoice_inc', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='出票单位')),
                ('fee_exam', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='考试费')),
                ('fee_total', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='总费用')),
                ('fee_exam_extra', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='补考费')),
                ('fee_info', models.TextField(blank=True, default='空', max_length=128, null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '训练班交费信息',
                'verbose_name_plural': '训练班交费信息',
            },
        ),
        migrations.CreateModel(
            name='TrainTextbook',
            fields=[
                ('relate_trainingclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trainingClass.TrainBasic', verbose_name='学号')),
                ('text_basic', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='教材1')),
                ('text_basic2', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='教材2')),
                ('text_guide', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='培训指南')),
                ('text_manual', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员手册')),
                ('text_other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '训练班教材',
                'verbose_name_plural': '训练班教材',
            },
        ),
        migrations.CreateModel(
            name='TrainCertification',
            fields=[
                ('relate_trainingclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trainingClass.TrainBasic', verbose_name='学号')),
                ('cert_id', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='证书编号')),
                ('cert_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发证日期')),
                ('cert_draw_people', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='领取人')),
                ('cert_draw_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='领取时间')),
                ('cert_nation_id', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国证证书编号')),
                ('cert_nation_people', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国证证书领取人与日期')),
                ('cert_other', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingClass.TrainClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '训练班证书',
                'verbose_name_plural': '训练班证书',
            },
        ),
    ]
