# Generated by Django 2.2.5 on 2019-09-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_post', models.CharField(choices=[('在职', '在职'), ('离职', '离职')], max_length=10, verbose_name='职工状态')),
                ('personal_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('personal_gender', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=1, verbose_name='性别')),
                ('personal_id_num', models.CharField(max_length=20, verbose_name='身份证号')),
                ('personal_birth_date', models.DateField(verbose_name='出生日期')),
                ('personal_is_marry', models.CharField(choices=[('未婚', '未婚'), ('已婚', '已婚'), ('丧偶', '丧偶'), ('离婚', '离婚')], max_length=4, verbose_name='婚姻情况')),
                ('personal_status', models.CharField(choices=[('中共党员', '中共党员'), ('中共预备党员', '中共预备党员'), ('共青团员', '共青团员'), ('民革党员', '民革党员'), ('民盟党员', '民盟党员'), ('民建会员', '民建会员'), ('民进会员', '民进会员'), ('农工党党员', '农工党党员'), ('致公党党员', '致公党党员'), ('九三学社社员', '九三学社社员'), ('台盟盟员', '台盟盟员'), ('无党派人士', '无党派人士')], max_length=10, verbose_name='政治面貌')),
                ('personal_folk', models.CharField(max_length=5, verbose_name='民族')),
                ('personal_reg_location', models.CharField(max_length=20, verbose_name='户籍')),
                ('personal_soc_ins', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=2, verbose_name='是否缴纳社保')),
                ('personal_soc_ins_id', models.CharField(max_length=30, verbose_name='社保卡号')),
                ('personal_phone', models.CharField(max_length=12, verbose_name='电话')),
                ('personal_phone_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='其他联系方式')),
                ('personal_emer_people', models.CharField(blank=True, max_length=30, null=True, verbose_name='紧急联系人')),
                ('personal_emer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急电话')),
                ('personal_current_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='当前住址')),
                ('personal_on_market', models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=3, null=True, verbose_name='人才市场挂编')),
                ('work_set_rank_date', models.DateField(blank=True, null=True, verbose_name='职称评定时间')),
                ('work_hire_rank_aca_date', models.DateField(blank=True, null=True, verbose_name='院编员工职称聘用时间')),
                ('work_enter_date', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('work_dismiss_date', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('work_department', models.CharField(blank=True, max_length=128, null=True, verbose_name='部门')),
                ('work_duty', models.CharField(blank=True, max_length=128, null=True, verbose_name='行政职务')),
                ('work_duty_hire_date', models.DateField(blank=True, null=True, verbose_name='职务聘用时间')),
                ('work_hire_method', models.CharField(blank=True, choices=[('校编', '校编'), ('校合同制', '校合同制'), ('院编', '院编'), ('院聘', '院聘')], max_length=10, null=True, verbose_name='聘用方式')),
                ('work_position', models.CharField(blank=True, max_length=20, null=True, verbose_name='岗位')),
                ('work_title', models.CharField(blank=True, max_length=10, null=True, verbose_name='职称')),
                ('edu_background', models.CharField(max_length=50, verbose_name='学历')),
                ('edu_grade', models.CharField(choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士'), ('专科', '专科'), ('其他', '其他')], max_length=5, verbose_name='学位')),
                ('edu_learn_exp', models.TextField(blank=True, null=True, verbose_name='学习经历')),
                ('other_more', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '员工母类',
                'verbose_name_plural': '员工母类',
            },
        ),
        migrations.CreateModel(
            name='AllStaff',
            fields=[
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.staff',),
        ),
        migrations.CreateModel(
            name='CurrentStaff',
            fields=[
            ],
            options={
                'verbose_name': '在职员工',
                'verbose_name_plural': '在职员工',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.staff',),
        ),
        migrations.CreateModel(
            name='DismissStaff',
            fields=[
            ],
            options={
                'verbose_name': '离职员工',
                'verbose_name_plural': '离职员工',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.staff',),
        ),
    ]
