# Generated by Django 2.2.5 on 2019-10-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstaff',
            options={'verbose_name': '全部员工', 'verbose_name_plural': '员工'},
        ),
    ]
