# Generated by Django 2.2.5 on 2019-10-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20191025_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyteacher',
            name='teacher_date',
            field=models.CharField(max_length=128, verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_date',
            field=models.CharField(max_length=128, verbose_name='上课时间'),
        ),
    ]
