# Generated by Django 2.2.5 on 2019-11-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20191026_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyteacher',
            name='teacher_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.FamilyClass', verbose_name='教师上课班级'),
        ),
    ]
