# Generated by Django 2.2.5 on 2019-10-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_fakemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakemodel',
            options={'verbose_name': '文件管理', 'verbose_name_plural': '文件管理'},
        ),
    ]
