# Generated by Django 2.2.5 on 2019-10-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0014_auto_20191028_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='rank',
            field=models.IntegerField(blank=True, max_length=128, null=True, verbose_name='显示顺序'),
        ),
    ]
