# Generated by Django 2.2.5 on 2019-10-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_folder_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='显示顺序'),
        ),
    ]
