# Generated by Django 2.2.5 on 2020-05-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_number', models.CharField(max_length=128, unique=True, verbose_name='学号')),
                ('tea_name', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='姓名')),
                ('tea_gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='空', max_length=16, null=True, verbose_name='性别')),
                ('tea_id_number', models.CharField(default='空', max_length=128, verbose_name='身份证号')),
                ('tea_loc', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='所在地')),
                ('tea_deg', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学历')),
                ('tea_major', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='专业')),
                ('tea_company', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='工作单位')),
                ('tea_duty', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职务')),
                ('tea_status', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职称')),
                ('tea_origin', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='生源来源')),
                ('tea_cellphone', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='手机号')),
                ('tea_wechat', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信')),
                ('tea_qq', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='QQ')),
                ('tea_signup_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='报名日期')),
                ('tea_signup_people', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='具体招生人')),
                ('tea_teacher_level', models.CharField(blank=True, default='空', max_length=32, null=True, verbose_name='心师级别')),
                ('tea_other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('tea_class_num', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='班内序号')),
            ],
            options={
                'verbose_name': '团体心理辅导招生信息',
                'verbose_name_plural': '团体心理辅导招生信息',
            },
        ),
        migrations.CreateModel(
            name='TeamClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=64, verbose_name='班级名')),
                ('class_index', models.IntegerField(blank=True, null=True, verbose_name='班级序号')),
                ('class_id_example', models.CharField(blank=True, max_length=128, null=True, verbose_name='学号命名')),
                ('class_recruit_teacher', models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='招生老师')),
                ('class_teacher', models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='跟班老师')),
                ('class_date', models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='开班年份')),
            ],
            options={
                'verbose_name': '团体心理辅导班级',
                'verbose_name_plural': '团体心理辅导班级',
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.TeamBasic', verbose_name='学生')),
            ],
            options={
                'verbose_name': '团体心理辅导信息总览',
                'verbose_name_plural': '团体心理辅导信息总览',
            },
        ),
        migrations.CreateModel(
            name='TeamOnduty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onduty', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='出勤')),
                ('homework', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业打卡')),
                ('other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamClass', verbose_name='班级')),
                ('relate_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '团体心理辅导考勤信息',
                'verbose_name_plural': '团体心理辅导考勤信息',
            },
        ),
        migrations.CreateModel(
            name='TeamExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='考试批次')),
                ('exam_total', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='总分')),
                ('exam_nation', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国考笔试成绩')),
                ('exam_practice', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='实操考核成绩')),
                ('other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamClass', verbose_name='班级')),
                ('relate_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamBasic', verbose_name='学号')),
            ],
            options={
                'verbose_name': '团体心理辅导考核成绩',
                'verbose_name_plural': '团体心理辅导考核成绩',
            },
        ),
        migrations.AddField(
            model_name='teambasic',
            name='tea_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.TeamClass', verbose_name='班级'),
        ),
        migrations.CreateModel(
            name='TeamWechat',
            fields=[
                ('relate_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.TeamBasic', verbose_name='学号')),
                ('wechat_number', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='平台绑定号码')),
                ('wechat_nickname', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信昵称')),
                ('wechat_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='开通日期')),
                ('wechat_other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '团体心理辅导365开通情况',
                'verbose_name_plural': '团体心理辅导365开通情况',
            },
        ),
        migrations.CreateModel(
            name='TeamTuition',
            fields=[
                ('relate_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.TeamBasic', verbose_name='学号')),
                ('fee_train', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='培训费')),
                ('fee_material', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='教材费')),
                ('fee_exam', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='考试费')),
                ('fee_total', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='总费用')),
                ('fee_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费日期')),
                ('fee_method', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费方式')),
                ('fee_tax', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票号')),
                ('fee_invoice_header', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票抬头')),
                ('fee_invoice_id', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票机构代码')),
                ('fee_invoice_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票开票日期')),
                ('fee_other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '团体心理辅导交费信息',
                'verbose_name_plural': '团体心理辅导交费信息',
            },
        ),
        migrations.CreateModel(
            name='TeamTextbook',
            fields=[
                ('relate_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.TeamBasic', verbose_name='学号')),
                ('text_team', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='团体心理辅导')),
                ('text_two', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='教材2')),
                ('text_train', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='培训指南')),
                ('text_manual', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员手册')),
                ('text_other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '团体心理辅导教材',
                'verbose_name_plural': '团体心理辅导教材',
            },
        ),
        migrations.CreateModel(
            name='TeamCertification',
            fields=[
                ('relate_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.TeamBasic', verbose_name='学号')),
                ('ass_cert_id', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会证书编号')),
                ('ass_cert_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会证书发证日期')),
                ('ass_cert_draw_people', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会证书领取人')),
                ('ass_cert_draw_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会证书领取时间')),
                ('nation_cert_id', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国证证书编号')),
                ('nation_cert_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国征证书发证日期')),
                ('nation_cert_draw_people', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国证证书领取人')),
                ('nation_cert_draw_date', models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国证证书领取时间')),
                ('other', models.TextField(blank=True, default='空', null=True, verbose_name='备注')),
                ('relate_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '团体心理辅导证书',
                'verbose_name_plural': '团体心理辅导证书',
            },
        ),
    ]
