# Generated by Django 2.2.5 on 2020-05-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teambasic',
            name='tea_qq',
        ),
        migrations.AddField(
            model_name='teambasic',
            name='tea_email',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='teambasic',
            name='tea_group',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='组别和职务'),
        ),
        migrations.AddField(
            model_name='teambasic',
            name='tea_type',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员类型'),
        ),
    ]
