# Generated by Django 2.2.5 on 2020-05-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200511_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teambasic',
            name='tea_teacher_level',
        ),
    ]
