# Generated by Django 2.2.5 on 2020-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_teambasic_tea_teacher_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamexam',
            name='batch',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='考试时间'),
        ),
    ]
