# Generated by Django 2.2.5 on 2019-10-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_number', models.CharField(max_length=128, unique=True, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=128, verbose_name='姓名')),
                ('stu_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=16, verbose_name='性别')),
                ('stu_id_number', models.CharField(max_length=128, unique=True, verbose_name='身份证号')),
                ('stu_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='所在地')),
                ('stu_deg', models.CharField(blank=True, max_length=128, null=True, verbose_name='学历')),
                ('stu_major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('stu_company', models.CharField(blank=True, max_length=128, null=True, verbose_name='工作单位')),
                ('stu_duty', models.CharField(blank=True, max_length=128, null=True, verbose_name='职务')),
                ('stu_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='职称')),
                ('stu_profession', models.CharField(blank=True, max_length=128, null=True, verbose_name='所属行业')),
                ('stu_origin', models.CharField(blank=True, max_length=128, null=True, verbose_name='生源来源')),
                ('stu_cellphone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号')),
                ('stu_wechat', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信')),
                ('stu_qq', models.CharField(blank=True, max_length=128, null=True, verbose_name='QQ')),
                ('stu_signup_date', models.DateField(blank=True, null=True, verbose_name='报名日期')),
                ('stu_signup_people', models.CharField(blank=True, max_length=128, null=True, verbose_name='具体招生人')),
                ('stu_other', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher', models.CharField(blank=True, max_length=64, null=True, verbose_name='负责老师')),
                ('class_date', models.CharField(blank=True, max_length=64, null=True, verbose_name='开班年份')),
                ('class_name', models.CharField(max_length=64, verbose_name='班级名')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='StudentCertification',
            fields=[
                ('relate_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号')),
                ('cert_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='证书编号')),
                ('cert_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('cert_draw_people', models.CharField(blank=True, max_length=128, null=True, verbose_name='领取人')),
                ('cert_draw_date', models.DateField(blank=True, null=True, verbose_name='领取时间')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('relate_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='报考日期')),
                ('exam_theory', models.CharField(blank=True, max_length=128, null=True, verbose_name='理论报考')),
                ('exam_theory_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='理论成绩')),
                ('exam_practise', models.CharField(blank=True, max_length=128, null=True, verbose_name='实操报考')),
                ('exam_practise_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='实操成绩')),
                ('exam_total', models.CharField(blank=True, max_length=128, null=True, verbose_name='综合报考')),
                ('exam_total_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='综合成绩')),
                ('exam_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='合格情况')),
            ],
            options={
                'verbose_name': '报考情况',
                'verbose_name_plural': '报考情况',
            },
        ),
        migrations.CreateModel(
            name='StudentExamExtra',
            fields=[
                ('relate_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='报考日期')),
                ('exam_theory', models.CharField(blank=True, max_length=128, null=True, verbose_name='理论报考')),
                ('exam_theory_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='理论成绩')),
                ('exam_practise', models.CharField(blank=True, max_length=128, null=True, verbose_name='实操报考')),
                ('exam_practise_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='实操成绩')),
                ('exam_total', models.CharField(blank=True, max_length=128, null=True, verbose_name='综合报考')),
                ('exam_total_result', models.CharField(blank=True, max_length=128, null=True, verbose_name='综合成绩')),
                ('exam_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='合格情况')),
            ],
            options={
                'verbose_name': '补考情况',
                'verbose_name_plural': '补考情况',
            },
        ),
        migrations.CreateModel(
            name='StudentTextbook',
            fields=[
                ('relate_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号')),
                ('text_basic', models.CharField(blank=True, max_length=128, null=True, verbose_name='基础技能')),
                ('text_sec', models.CharField(blank=True, max_length=128, null=True, verbose_name='二级技能')),
                ('text_sec_exer', models.CharField(blank=True, max_length=128, null=True, verbose_name='二级习题')),
                ('text_sec_measure', models.CharField(blank=True, max_length=128, null=True, verbose_name='二级量表')),
                ('text_thr', models.CharField(blank=True, max_length=128, null=True, verbose_name='三级技能')),
                ('text_thr_exer', models.CharField(blank=True, max_length=128, null=True, verbose_name='三级习题')),
                ('text_manual', models.CharField(blank=True, max_length=128, null=True, verbose_name='学员手册')),
                ('text_exam', models.CharField(blank=True, max_length=128, null=True, verbose_name='模拟试卷')),
                ('text_other', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
            },
        ),
        migrations.CreateModel(
            name='StudentWechat',
            fields=[
                ('relate_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号')),
                ('wechat_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='平台绑定号码')),
                ('wechat_nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信昵称')),
                ('wechat_date', models.DateField(blank=True, null=True, verbose_name='开通日期')),
                ('wechat_onduty', models.CharField(blank=True, max_length=128, null=True, verbose_name='出勤')),
                ('wechat_homework', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业打卡')),
                ('wechat_other', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '365开通情况',
                'verbose_name_plural': '365开通情况',
            },
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('relate_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号')),
                ('fee_train', models.CharField(blank=True, max_length=128, null=True, verbose_name='培训费')),
                ('fee_material', models.CharField(blank=True, max_length=128, null=True, verbose_name='资料费')),
                ('fee_exam', models.CharField(blank=True, max_length=128, null=True, verbose_name='考试费')),
                ('fee_total', models.CharField(blank=True, max_length=128, null=True, verbose_name='总费用')),
                ('fee_exam_extra', models.CharField(blank=True, max_length=128, null=True, verbose_name='补考费')),
                ('fee_date', models.DateField(blank=True, null=True, verbose_name='缴费日期')),
                ('fee_method', models.CharField(blank=True, max_length=128, null=True, verbose_name='缴费方式')),
                ('fee_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='收据号')),
            ],
            options={
                'verbose_name': '交费信息',
                'verbose_name_plural': '交费信息',
            },
        ),
        migrations.AddField(
            model_name='studentbasic',
            name='stu_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
    ]
