# Generated by Django 2.2.5 on 2019-10-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191017_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='学号'),
        ),
    ]
