# Generated by Django 2.2.5 on 2019-10-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191017_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexam',
            options={'verbose_name': '考试信息', 'verbose_name_plural': '考试信息'},
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_recruit_teacher',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='招生老师'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='管班老师'),
        ),
    ]
