# Generated by Django 2.2.5 on 2019-10-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191019_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwechat',
            name='wechat_homework',
        ),
        migrations.RemoveField(
            model_name='studentwechat',
            name='wechat_onduty',
        ),
        migrations.RemoveField(
            model_name='studentwechat',
            name='wechat_other',
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='跟班老师'),
        ),
        migrations.CreateModel(
            name='Onduty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onduty', models.CharField(blank=True, max_length=128, null=True, verbose_name='出勤')),
                ('homework', models.CharField(blank=True, max_length=128, null=True, verbose_name='作业打卡')),
                ('other', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('relate_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentBasic', verbose_name='学号')),
            ],
        ),
    ]
