# Generated by Django 2.2.5 on 2019-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191021_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='fee_tax',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='发票号'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_level',
            field=models.CharField(blank=True, choices=[('二级', '二级'), ('三级', '三级')], max_length=16, null=True, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_status',
            field=models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], max_length=128, null=True, verbose_name='合格情况'),
        ),
    ]
