# Generated by Django 2.2.5 on 2019-10-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20191021_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbasic',
            name='stu_class_num',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='班内序号'),
        ),
    ]
