# Generated by Django 2.2.5 on 2019-10-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentbasic_stu_class_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onduty',
            options={'verbose_name': '学员考勤信息', 'verbose_name_plural': '学员考勤信息'},
        ),
        migrations.AlterModelOptions(
            name='studentbasic',
            options={'verbose_name': '学员招生信息', 'verbose_name_plural': '学员招生信息'},
        ),
        migrations.AlterModelOptions(
            name='studentcertification',
            options={'verbose_name': '学员证书', 'verbose_name_plural': '学员证书'},
        ),
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name': '学员班级', 'verbose_name_plural': '学员班级'},
        ),
        migrations.AlterModelOptions(
            name='studentexam',
            options={'verbose_name': '学员考试信息', 'verbose_name_plural': '学员考试信息'},
        ),
        migrations.AlterModelOptions(
            name='studentexamextra',
            options={'verbose_name': '学员补考情况', 'verbose_name_plural': '学员补考情况'},
        ),
        migrations.AlterModelOptions(
            name='studenttextbook',
            options={'verbose_name': '学员教材', 'verbose_name_plural': '学员教材'},
        ),
        migrations.AlterModelOptions(
            name='studentwechat',
            options={'verbose_name': '学员365开通情况', 'verbose_name_plural': '学员365开通情况'},
        ),
        migrations.AlterModelOptions(
            name='tuition',
            options={'verbose_name': '学员交费信息', 'verbose_name_plural': '学员交费信息'},
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_signup_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='报名日期'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='cert_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='发证日期'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='报考日期'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='报考日期'),
        ),
        migrations.AlterField(
            model_name='studentwechat',
            name='wechat_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='开通日期'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='缴费日期'),
        ),
    ]
