# Generated by Django 2.2.5 on 2019-10-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20191024_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcertification',
            name='cert_draw_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='领取时间'),
        ),
    ]
