# Generated by Django 2.2.5 on 2019-10-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20191024_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onduty',
            options={'verbose_name': '心理学员考勤信息', 'verbose_name_plural': '心理学员考勤信息'},
        ),
        migrations.AlterModelOptions(
            name='studentbasic',
            options={'verbose_name': '心理学员招生信息', 'verbose_name_plural': '心理学员招生信息'},
        ),
        migrations.AlterModelOptions(
            name='studentcertification',
            options={'verbose_name': '心理学员证书', 'verbose_name_plural': '心理学员证书'},
        ),
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name': '心理学员班级', 'verbose_name_plural': '心理学员班级'},
        ),
        migrations.AlterModelOptions(
            name='studentexam',
            options={'verbose_name': '心理学员考试信息', 'verbose_name_plural': '心理学员考试信息'},
        ),
        migrations.AlterModelOptions(
            name='studentexamextra',
            options={'verbose_name': '心理学员补考情况', 'verbose_name_plural': '心理学员补考情况'},
        ),
        migrations.AlterModelOptions(
            name='studenttextbook',
            options={'verbose_name': '心理学员教材', 'verbose_name_plural': '心理学员教材'},
        ),
        migrations.AlterModelOptions(
            name='studentwechat',
            options={'verbose_name': '心理学员365开通情况', 'verbose_name_plural': '心理学员365开通情况'},
        ),
        migrations.AlterModelOptions(
            name='tuition',
            options={'verbose_name': '心理学员交费信息', 'verbose_name_plural': '心理学员交费信息'},
        ),
    ]
