# Generated by Django 2.2.5 on 2019-10-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20191026_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.StudentBasic', verbose_name='学生')),
            ],
            options={
                'verbose_name': '心理学员招生信息总览',
                'verbose_name_plural': '心理学员招生信息总览',
            },
        ),
    ]
