# Generated by Django 2.2.5 on 2019-10-29 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='tuition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Tuition', verbose_name='财务信息'),
            preserve_default=False,
        ),
    ]
