# Generated by Django 2.2.5 on 2019-10-29 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_total_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='tuition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Tuition', verbose_name='财务信息'),
        ),
    ]
