# Generated by Django 2.2.5 on 2019-10-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20191029_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onduty',
            name='relate_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentBasic', verbose_name='学号'),
        ),
    ]
