# Generated by Django 2.2.5 on 2019-10-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20191029_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='tuition',
        ),
    ]
