# Generated by Django 2.2.5 on 2019-10-31 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_total_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onduty',
            name='homework',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='作业打卡'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='onduty',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='other',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_cellphone',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_class',
            field=models.ForeignKey(default='空', on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_class_num',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='班内序号'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_company',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='工作单位'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_deg',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_duty',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='空', max_length=16, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_id_number',
            field=models.CharField(default='空', max_length=128, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_level',
            field=models.CharField(blank=True, choices=[('二级', '二级'), ('三级', '三级')], default='空', max_length=16, null=True, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_loc',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_major',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_name',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_origin',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='生源来源'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_other',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_qq',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_signup_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='报名日期'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_signup_people',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='具体招生人'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_status',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_wechat',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='cert_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发证日期'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='cert_draw_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='cert_draw_people',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='领取人'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='cert_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='证书编号'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='relate_student',
            field=models.OneToOneField(default='空', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_date',
            field=models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='开班年份'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_recruit_teacher',
            field=models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='招生老师'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_teacher',
            field=models.CharField(blank=True, default='空', max_length=64, null=True, verbose_name='跟班老师'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='报考日期'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_practise',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='实操报考'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_practise_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='实操成绩'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_status',
            field=models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], default='空', max_length=128, null=True, verbose_name='合格情况'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_theory',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='理论报考'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_theory_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='理论成绩'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_total',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='综合报考'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_total_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='综合成绩'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='报考日期'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_practise',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='实操报考'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_practise_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='实操成绩'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_status',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='合格情况'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_theory',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='理论报考'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_theory_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='理论成绩'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_total',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='综合报考'),
        ),
        migrations.AlterField(
            model_name='studentexamextra',
            name='exam_total_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='综合成绩'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_basic',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='基础技能'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_exam',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='模拟试卷'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_manual',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员手册'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_other',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_sec',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='二级技能'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_sec_exer',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='二级习题'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_sec_measure',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='二级量表'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_thr',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='三级技能'),
        ),
        migrations.AlterField(
            model_name='studenttextbook',
            name='text_thr_exer',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='三级习题'),
        ),
        migrations.AlterField(
            model_name='studentwechat',
            name='wechat_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='开通日期'),
        ),
        migrations.AlterField(
            model_name='studentwechat',
            name='wechat_nickname',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='微信昵称'),
        ),
        migrations.AlterField(
            model_name='studentwechat',
            name='wechat_number',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='平台绑定号码'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费日期'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_exam',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='考试费'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_exam_extra',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='补考费'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='收据号'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_material',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='资料费'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_method',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='缴费方式'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_tax',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='发票号'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_total',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='总费用'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='fee_train',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='培训费'),
        ),
    ]
