# Generated by Django 2.2.5 on 2019-11-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20191031_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_level',
            field=models.CharField(blank=True, choices=[('二级', '二级'), ('三级', '三级'), ('三升二', '三升二')], default='空', max_length=16, null=True, verbose_name='级别'),
        ),
    ]
