# Generated by Django 2.2.5 on 2019-11-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20191102_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='onduty',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='班级序号'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentexamextra',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studenttextbook',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentwechat',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='relate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentClass', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='relate_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentBasic', verbose_name='学号'),
        ),
    ]
