# Generated by Django 2.2.5 on 2019-11-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20191109_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='class_id_example',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='学号命名'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_id_number',
            field=models.CharField(default='空', max_length=128, verbose_name='身份证号'),
        ),
    ]
