# Generated by Django 2.2.5 on 2019-11-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20191109_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttextbook',
            name='text_sec_measure_third',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='三级量表'),
        ),
    ]
