# Generated by Django 2.2.5 on 2019-11-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_studenttextbook_text_sec_measure_third'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttextbook',
            old_name='text_sec_measure_third',
            new_name='text_thr_measure',
        ),
    ]
