# Generated by Django 2.2.5 on 2019-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20191123_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_level',
            field=models.CharField(blank=True, choices=[('二级', '二级'), ('三级', '三级'), ('中科院', '中科院'), ('心理辅导师', '心理辅导师')], default='空', max_length=16, null=True, verbose_name='级别'),
        ),
    ]
