# Generated by Django 2.2.5 on 2020-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20200509_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcertification',
            name='cert_CAS_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='中科院证书编号'),
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='cert_CAS_people',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='中科院证书领取人与领取日期'),
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='cert_nation_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国证证书编号'),
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='cert_nation_people',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国证领取人与领取日期'),
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='cert_other',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_CAS',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='中科院成绩'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_other',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_practise_result2',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='实操笔试分'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_pre',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='说课分'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_sec_skill',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会二级技能'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_sec_theory',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会二级理论'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_speech',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='宣讲分'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_thesis',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会论文答辩'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_thr_skill',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会三级技能'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_thr_theory',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会三级理论'),
        ),
        migrations.AddField(
            model_name='studentwechat',
            name='wechat_date2',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='开通日期2'),
        ),
        migrations.AddField(
            model_name='studentwechat',
            name='wechat_test',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='开通心理测评'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='homework',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='视频提交'),
        ),
        migrations.AlterField(
            model_name='studentcertification',
            name='cert_id',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='协会证书编号'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_date',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='参试时间'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_practise',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国考实操报考'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_practise_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国考实操成绩'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_theory',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国考理论报考'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam_theory_result',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='国考理论成绩'),
        ),
    ]
