# Generated by Django 2.2.5 on 2020-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20200516_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_group',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='组别与职务'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stu_type',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='学员类型'),
        ),
    ]
