from .classmodel import *
from .teammodel import *
from .tuitionmodel import *
from .textbookmodel import *
from .wechatmodel import *
from .exammodel import *
from .certificationmodel import *
from .ondutymodel import *
from .totalmodel import *