# Generated by Django 2.2.5 on 2021-03-08 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarriageBasic',
            new_name='SocialBasic',
        ),
        migrations.RenameModel(
            old_name='MarriageCertification',
            new_name='SocialCertification',
        ),
        migrations.RenameModel(
            old_name='MarriageClass',
            new_name='SocialClass',
        ),
        migrations.RenameModel(
            old_name='MarriageExam',
            new_name='SocialExam',
        ),
        migrations.RenameModel(
            old_name='MarriageOnduty',
            new_name='SocialOnduty',
        ),
        migrations.RenameModel(
            old_name='MarriageTextbook',
            new_name='SocialTextbook',
        ),
        migrations.RenameModel(
            old_name='MarriageTuition',
            new_name='SocialTuition',
        ),
        migrations.RenameModel(
            old_name='MarriageWechat',
            new_name='SocialWechat',
        ),
        migrations.AlterModelOptions(
            name='socialbasic',
            options={'verbose_name': '社会工作师招生信息', 'verbose_name_plural': '社会工作师招生信息'},
        ),
        migrations.AlterModelOptions(
            name='socialcertification',
            options={'verbose_name': '社会工作师证书', 'verbose_name_plural': '社会工作师证书'},
        ),
        migrations.AlterModelOptions(
            name='socialclass',
            options={'verbose_name': '社会工作师班级', 'verbose_name_plural': '社会工作师班级'},
        ),
        migrations.AlterModelOptions(
            name='socialexam',
            options={'verbose_name': '社会工作师考核成绩', 'verbose_name_plural': '社会工作师考核成绩'},
        ),
        migrations.AlterModelOptions(
            name='socialonduty',
            options={'verbose_name': '社会工作师考勤信息', 'verbose_name_plural': '社会工作师考勤信息'},
        ),
        migrations.AlterModelOptions(
            name='socialtextbook',
            options={'verbose_name': '社会工作师教材', 'verbose_name_plural': '社会工作师教材'},
        ),
        migrations.AlterModelOptions(
            name='socialtuition',
            options={'verbose_name': '社会工作师交费信息', 'verbose_name_plural': '社会工作师交费信息'},
        ),
        migrations.AlterModelOptions(
            name='socialwechat',
            options={'verbose_name': '社会工作师365开通情况', 'verbose_name_plural': '社会工作师365开通情况'},
        ),
        migrations.AlterModelOptions(
            name='total',
            options={'verbose_name': '社会工作师信息总览', 'verbose_name_plural': '社会工作师信息总览'},
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_cellphone',
            new_name='social_cellphone',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_class',
            new_name='social_class',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_class_num',
            new_name='social_class_num',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_company',
            new_name='social_company',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_deg',
            new_name='social_deg',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_duty',
            new_name='social_duty',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_email',
            new_name='social_email',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_gender',
            new_name='social_gender',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_group',
            new_name='social_group',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_id_number',
            new_name='social_id_number',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_loc',
            new_name='social_loc',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_major',
            new_name='social_major',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_name',
            new_name='social_name',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_origin',
            new_name='social_origin',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_other',
            new_name='social_other',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_signup_date',
            new_name='social_signup_date',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_signup_people',
            new_name='social_signup_people',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_status',
            new_name='social_status',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_type',
            new_name='social_type',
        ),
        migrations.RenameField(
            model_name='socialbasic',
            old_name='mar_wechat',
            new_name='social_wechat',
        ),
        migrations.RenameField(
            model_name='socialcertification',
            old_name='relate_marriage',
            new_name='relate_social',
        ),
        migrations.RenameField(
            model_name='socialonduty',
            old_name='relate_marriage',
            new_name='relate_social',
        ),
        migrations.RenameField(
            model_name='socialtextbook',
            old_name='relate_marriage',
            new_name='relate_social',
        ),
        migrations.RenameField(
            model_name='socialtuition',
            old_name='relate_marriage',
            new_name='relate_social',
        ),
        migrations.RenameField(
            model_name='socialwechat',
            old_name='relate_marriage',
            new_name='relate_social',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='marriage',
            new_name='social',
        ),
        migrations.RemoveField(
            model_name='socialbasic',
            name='mar_number',
        ),
        migrations.RemoveField(
            model_name='socialexam',
            name='relate_marriage',
        ),
        migrations.AddField(
            model_name='socialbasic',
            name='social_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialexam',
            name='relate_social',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.SocialBasic', verbose_name='学号'),
        ),
    ]
