from .classmodel import *
from .studentmodel import *
from .tuitionmodel import *
from .textbookmodel import *
from .wechatmodel import *
from .exammodel import *
from .examextramodel import *
from .certificationmodel import *
from .ondutymodel import *